#############################################################################
# Makefile for building: Browser-mk2
# Generated by qmake (3.1) (Qt 6.7.2)
# Project:  Browser-mk2.pro
# Template: app
# Command: /usr/lib64/qt6/bin/qmake6 -o Makefile Browser-mk2.pro -spec linux-g++ CONFIG-=qml_debug CONFIG+=qtquickcompiler CONFIG+=force_debug_info CONFIG+=separate_debug_info
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_MESSAGELOGCONTEXT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WEBENGINEWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_QMLINTEGRATION_LIB -DQT_POSITIONING_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -g -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O3 -pipe -march=native -ftree-vectorize -fno-predictive-commoning -fno-semantic-interposition -floop-nest-optimize -fipa-pta -fdevirtualize-at-ltrans -Wall -Wextra -Wpedantic -flto=6 -O2 -g -std=gnu++1z -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I. -I/usr/lib64/qt6/mkspecs/linux-g++
QMAKE         = /usr/lib64/qt6/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib64/qt6/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/lib64/qt6/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Browser-mk21.0.0
DISTDIR = /home/daiyousei/sources/gizmoduck/.tmp/Browser-mk21.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib64 -Wl,-rpath-link,/usr/lib64
LIBS          = $(SUBLIBS) -ljemalloc -ltoxcore -lsodium /usr/lib64/libQt6WebEngineWidgets.so /usr/lib64/libQt6PrintSupport.so /usr/lib64/libQt6Widgets.so /usr/lib64/libQt6WebEngineCore.so /usr/lib64/libQt6Quick.so /usr/lib64/libQt6OpenGL.so /usr/lib64/libQt6Gui.so /usr/lib64/libGLX.so /usr/lib64/libOpenGL.so /usr/lib64/libQt6QmlModels.so /usr/lib64/libQt6WebChannel.so /usr/lib64/libQt6Qml.so /usr/lib64/libQt6QmlBuiltins.a /usr/lib64/libQt6Network.so /usr/lib64/libQt6Positioning.so /usr/lib64/libQt6Sql.so /usr/lib64/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		browser_mainwindow.cpp \
		fullscreen.cpp \
		input_widget.cpp \
		message_log.cpp \
		tab_manager.cpp \
		webview.cpp \
		navigation_button.cpp \
		webpage.cpp \
		file_dialog.cpp \
		side_tabs.cpp \
		settings_tab.cpp \
		debug_tab.cpp \
		userscript.cpp \
		request_filter.cpp \
		tox_client.c \
		tox_ui.cpp res_scripts_custom_css_js.cpp \
		qmlcache_loader.cpp \
		qrc_browser_qmlcache.cpp \
		moc_browser_mainwindow.cpp \
		moc_fullscreen.cpp \
		moc_input_widget.cpp \
		moc_message_log.cpp \
		moc_tab_manager.cpp \
		moc_webview.cpp \
		moc_navigation_button.cpp \
		moc_webpage.cpp \
		moc_file_dialog.cpp \
		moc_request_filter.cpp \
		moc_side_tabs.cpp \
		moc_setting_tab.cpp \
		moc_debug_tab.cpp \
		moc_tox_ui.cpp
OBJECTS       = main.o \
		browser_mainwindow.o \
		fullscreen.o \
		input_widget.o \
		message_log.o \
		tab_manager.o \
		webview.o \
		navigation_button.o \
		webpage.o \
		file_dialog.o \
		side_tabs.o \
		settings_tab.o \
		debug_tab.o \
		userscript.o \
		request_filter.o \
		tox_client.o \
		tox_ui.o \
		res_scripts_custom_css_js.o \
		qmlcache_loader.o \
		qrc_browser_qmlcache.o \
		moc_browser_mainwindow.o \
		moc_fullscreen.o \
		moc_input_widget.o \
		moc_message_log.o \
		moc_tab_manager.o \
		moc_webview.o \
		moc_navigation_button.o \
		moc_webpage.o \
		moc_file_dialog.o \
		moc_request_filter.o \
		moc_side_tabs.o \
		moc_setting_tab.o \
		moc_debug_tab.o \
		moc_tox_ui.o
DIST          = /usr/lib64/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt6/mkspecs/common/unix.conf \
		/usr/lib64/qt6/mkspecs/common/linux.conf \
		/usr/lib64/qt6/mkspecs/common/sanitize.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt6/mkspecs/common/g++-base.conf \
		/usr/lib64/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt6/mkspecs/qconfig.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlbuiltins.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlbuiltins_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt6/mkspecs/features/qt_config.prf \
		/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt6/mkspecs/features/toolchain.prf \
		/usr/lib64/qt6/mkspecs/features/default_pre.prf \
		/usr/lib64/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt6/mkspecs/features/default_post.prf \
		/usr/lib64/qt6/mkspecs/features/resolve_target.prf \
		/usr/lib64/qt6/mkspecs/features/unix/separate_debug_info.prf \
		/usr/lib64/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib64/qt6/mkspecs/features/qtquickcompiler.prf \
		/usr/lib64/qt6/mkspecs/features/warn_on.prf \
		/usr/lib64/qt6/mkspecs/features/permissions.prf \
		/usr/lib64/qt6/mkspecs/features/qt.prf \
		/usr/lib64/qt6/mkspecs/features/resources.prf \
		/usr/lib64/qt6/mkspecs/features/moc.prf \
		/usr/lib64/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt6/mkspecs/features/uic.prf \
		/usr/lib64/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt6/mkspecs/features/file_copies.prf \
		/usr/lib64/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt6/mkspecs/features/exceptions.prf \
		/usr/lib64/qt6/mkspecs/features/yacc.prf \
		/usr/lib64/qt6/mkspecs/features/lex.prf \
		Browser-mk2.pro browser_mainwindow.h \
		fullscreen.h \
		input_widget.h \
		message_log.h \
		tab_groups.h \
		tab_manager.h \
		webview.h \
		navigation_button.h \
		webpage.h \
		file_dialog.h \
		request_filter.h \
		side_tabs.h \
		setting_tab.h \
		debug_tab.h \
		userscript.h \
		tox_client.h \
		tox_ui.h main.cpp \
		browser_mainwindow.cpp \
		fullscreen.cpp \
		input_widget.cpp \
		message_log.cpp \
		tab_manager.cpp \
		webview.cpp \
		navigation_button.cpp \
		webpage.cpp \
		file_dialog.cpp \
		side_tabs.cpp \
		settings_tab.cpp \
		debug_tab.cpp \
		userscript.cpp \
		request_filter.cpp \
		tox_client.c \
		tox_ui.cpp
QMAKE_TARGET  = Browser-mk2
DESTDIR       = 
TARGET        = Browser-mk2


first: all
####### Build rules

Browser-mk2:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)
	objcopy --only-keep-debug Browser-mk2 Browser-mk2.debug && objcopy --strip-debug Browser-mk2 && objcopy --add-gnu-debuglink=Browser-mk2.debug Browser-mk2 && chmod -x Browser-mk2.debug

Makefile: Browser-mk2.pro /usr/lib64/qt6/mkspecs/linux-g++/qmake.conf /usr/lib64/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt6/mkspecs/common/unix.conf \
		/usr/lib64/qt6/mkspecs/common/linux.conf \
		/usr/lib64/qt6/mkspecs/common/sanitize.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt6/mkspecs/common/g++-base.conf \
		/usr/lib64/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt6/mkspecs/qconfig.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlbuiltins.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlbuiltins_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt6/mkspecs/features/qt_config.prf \
		/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt6/mkspecs/features/toolchain.prf \
		/usr/lib64/qt6/mkspecs/features/default_pre.prf \
		/usr/lib64/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt6/mkspecs/features/default_post.prf \
		/usr/lib64/qt6/mkspecs/features/resolve_target.prf \
		/usr/lib64/qt6/mkspecs/features/unix/separate_debug_info.prf \
		/usr/lib64/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib64/qt6/mkspecs/features/qtquickcompiler.prf \
		/usr/lib64/qt6/mkspecs/features/warn_on.prf \
		/usr/lib64/qt6/mkspecs/features/permissions.prf \
		/usr/lib64/qt6/mkspecs/features/qt.prf \
		/usr/lib64/qt6/mkspecs/features/resources.prf \
		/usr/lib64/qt6/mkspecs/features/moc.prf \
		/usr/lib64/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt6/mkspecs/features/uic.prf \
		/usr/lib64/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt6/mkspecs/features/file_copies.prf \
		/usr/lib64/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt6/mkspecs/features/exceptions.prf \
		/usr/lib64/qt6/mkspecs/features/yacc.prf \
		/usr/lib64/qt6/mkspecs/features/lex.prf \
		Browser-mk2.pro \
		browser_qmlcache.qrc \
		/usr/lib64/libQt6WebEngineWidgets.prl \
		/usr/lib64/libQt6PrintSupport.prl \
		/usr/lib64/libQt6Widgets.prl \
		/usr/lib64/libQt6WebEngineCore.prl \
		/usr/lib64/libQt6Quick.prl \
		/usr/lib64/libQt6OpenGL.prl \
		/usr/lib64/libQt6Gui.prl \
		/usr/lib64/libQt6QmlModels.prl \
		/usr/lib64/libQt6WebChannel.prl \
		/usr/lib64/libQt6Qml.prl \
		/usr/lib64/libQt6Network.prl \
		/usr/lib64/libQt6Positioning.prl \
		/usr/lib64/libQt6Sql.prl \
		/usr/lib64/libQt6Core.prl
	$(QMAKE) -o Makefile Browser-mk2.pro -spec linux-g++ CONFIG-=qml_debug CONFIG+=qtquickcompiler CONFIG+=force_debug_info CONFIG+=separate_debug_info
/usr/lib64/qt6/mkspecs/features/spec_pre.prf:
/usr/lib64/qt6/mkspecs/common/unix.conf:
/usr/lib64/qt6/mkspecs/common/linux.conf:
/usr/lib64/qt6/mkspecs/common/sanitize.conf:
/usr/lib64/qt6/mkspecs/common/gcc-base.conf:
/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt6/mkspecs/common/g++-base.conf:
/usr/lib64/qt6/mkspecs/common/g++-unix.conf:
/usr/lib64/qt6/mkspecs/qconfig.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_charts.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_charts_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_pdfquick.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlbuiltins.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlbuiltins_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3d.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_shadertools.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_tools_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannelquick.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginequick.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt6/mkspecs/features/qt_functions.prf:
/usr/lib64/qt6/mkspecs/features/qt_config.prf:
/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt6/mkspecs/features/toolchain.prf:
/usr/lib64/qt6/mkspecs/features/default_pre.prf:
/usr/lib64/qt6/mkspecs/features/resolve_config.prf:
/usr/lib64/qt6/mkspecs/features/default_post.prf:
/usr/lib64/qt6/mkspecs/features/resolve_target.prf:
/usr/lib64/qt6/mkspecs/features/unix/separate_debug_info.prf:
/usr/lib64/qt6/mkspecs/features/resources_functions.prf:
/usr/lib64/qt6/mkspecs/features/qtquickcompiler.prf:
/usr/lib64/qt6/mkspecs/features/warn_on.prf:
/usr/lib64/qt6/mkspecs/features/permissions.prf:
/usr/lib64/qt6/mkspecs/features/qt.prf:
/usr/lib64/qt6/mkspecs/features/resources.prf:
/usr/lib64/qt6/mkspecs/features/moc.prf:
/usr/lib64/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt6/mkspecs/features/uic.prf:
/usr/lib64/qt6/mkspecs/features/unix/thread.prf:
/usr/lib64/qt6/mkspecs/features/qmake_use.prf:
/usr/lib64/qt6/mkspecs/features/file_copies.prf:
/usr/lib64/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt6/mkspecs/features/exceptions.prf:
/usr/lib64/qt6/mkspecs/features/yacc.prf:
/usr/lib64/qt6/mkspecs/features/lex.prf:
Browser-mk2.pro:
browser_qmlcache.qrc:
/usr/lib64/libQt6WebEngineWidgets.prl:
/usr/lib64/libQt6PrintSupport.prl:
/usr/lib64/libQt6Widgets.prl:
/usr/lib64/libQt6WebEngineCore.prl:
/usr/lib64/libQt6Quick.prl:
/usr/lib64/libQt6OpenGL.prl:
/usr/lib64/libQt6Gui.prl:
/usr/lib64/libQt6QmlModels.prl:
/usr/lib64/libQt6WebChannel.prl:
/usr/lib64/libQt6Qml.prl:
/usr/lib64/libQt6Network.prl:
/usr/lib64/libQt6Positioning.prl:
/usr/lib64/libQt6Sql.prl:
/usr/lib64/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Browser-mk2.pro -spec linux-g++ CONFIG-=qml_debug CONFIG+=qtquickcompiler CONFIG+=force_debug_info CONFIG+=separate_debug_info

qmake_all: FORCE


all: Makefile Browser-mk2

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res/scripts/custom_css.js $(DISTDIR)/
	$(COPY_FILE) --parents browser.qrc $(DISTDIR)/
	$(COPY_FILE) --parents browser_qmlcache.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents browser_mainwindow.h fullscreen.h input_widget.h message_log.h tab_groups.h tab_manager.h webview.h navigation_button.h webpage.h file_dialog.h request_filter.h side_tabs.h setting_tab.h debug_tab.h userscript.h tox_client.h tox_ui.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp browser_mainwindow.cpp fullscreen.cpp input_widget.cpp message_log.cpp tab_manager.cpp webview.cpp navigation_button.cpp webpage.cpp file_dialog.cpp side_tabs.cpp settings_tab.cpp debug_tab.cpp userscript.cpp request_filter.cpp tox_client.c tox_ui.cpp $(DISTDIR)/
	$(COPY_FILE) --parents gizmoduck_ru.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) /home/daiyousei/sources/gizmoduck/Browser-mk2.debug .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_qmlcache_make_all: res_scripts_custom_css_js.cpp
compiler_qmlcache_clean:
	-$(DEL_FILE) res_scripts_custom_css_js.cpp
res_scripts_custom_css_js.cpp: res/scripts/custom_css.js \
		/usr/lib64/qt6/libexec/qmlcachegen
	/usr/lib64/qt6/libexec/qmlcachegen --resource=/home/daiyousei/sources/gizmoduck/browser.qrc -o res_scripts_custom_css_js.cpp res/scripts/custom_css.js

compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
qmlcache_loader.cpp: browser.qrc /usr/lib64/qt6/libexec/qmlcachegen
	/usr/lib64/qt6/libexec/qmlcachegen --resource-file-mapping=/home/daiyousei/sources/gizmoduck/browser.qrc=/home/daiyousei/sources/gizmoduck/browser_qmlcache.qrc -o qmlcache_loader.cpp browser.qrc

compiler_rcc_make_all: qrc_browser_qmlcache.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_browser_qmlcache.cpp
qrc_browser_qmlcache.cpp: browser_qmlcache.qrc \
		/usr/lib64/qt6/libexec/rcc \
		gizmoduck_ru.qm \
		res/scripts/custom_css.js \
		res/icons/emblem-system-symbolic.svg \
		res/icons/network-vpn-acquiring-symbolic.svg \
		res/icons/go-up-symbolic.svg \
		res/icons/animagion.gif \
		res/icons/mail-attachment-symbolic.svg \
		res/icons/user-away-symbolic.svg \
		res/icons/go-down-symbolic.svg \
		res/icons/window-close-symbolic.svg \
		res/icons/media-playback-start-symbolic-rtl.svg \
		res/icons/user-available-symbolic.svg \
		res/icons/user-offline-symbolic.svg \
		res/icons/media-playback-start-symbolic.svg \
		res/icons/user-idle-symbolic.svg \
		res/icons/empty.png \
		res/icons/network-vpn-symbolic.svg \
		res/icons/weather-snow-symbolic.svg \
		res/icons/icon.png \
		res/icons/user-status-pending-symbolic.svg \
		res/icons/preferences-desktop-screensaver-symbolic.svg \
		res/icons/view-refresh-symbolic.svg \
		res/icons/user-invisible-symbolic.svg \
		res/icons/user-busy-symbolic.svg \
		res/icons/user-not-tracked-symbolic.svg
	/usr/lib64/qt6/libexec/rcc -name browser_qmlcache browser_qmlcache.qrc -o qrc_browser_qmlcache.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O3 -pipe -march=native -ftree-vectorize -fno-predictive-commoning -fno-semantic-interposition -floop-nest-optimize -fipa-pta -fdevirtualize-at-ltrans -Wall -Wextra -Wpedantic -flto=6 -O2 -g -std=gnu++1z -Wall -Wextra -fPIC -dM -E -o moc_predefs.h /usr/lib64/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_browser_mainwindow.cpp moc_fullscreen.cpp moc_input_widget.cpp moc_message_log.cpp moc_tab_manager.cpp moc_webview.cpp moc_navigation_button.cpp moc_webpage.cpp moc_file_dialog.cpp moc_request_filter.cpp moc_side_tabs.cpp moc_setting_tab.cpp moc_debug_tab.cpp moc_tox_ui.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_browser_mainwindow.cpp moc_fullscreen.cpp moc_input_widget.cpp moc_message_log.cpp moc_tab_manager.cpp moc_webview.cpp moc_navigation_button.cpp moc_webpage.cpp moc_file_dialog.cpp moc_request_filter.cpp moc_side_tabs.cpp moc_setting_tab.cpp moc_debug_tab.cpp moc_tox_ui.cpp
moc_browser_mainwindow.cpp: browser_mainwindow.h \
		navigation_button.h \
		tab_manager.h \
		webview.h \
		tab_groups.h \
		webpage.h \
		file_dialog.h \
		setting_tab.h \
		debug_tab.h \
		fullscreen.h \
		request_filter.h \
		tox_ui.h \
		input_widget.h \
		tox_client.h \
		side_tabs.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/daiyousei/sources/gizmoduck/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/daiyousei/sources/gizmoduck -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include browser_mainwindow.h -o moc_browser_mainwindow.cpp

moc_fullscreen.cpp: fullscreen.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/daiyousei/sources/gizmoduck/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/daiyousei/sources/gizmoduck -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include fullscreen.h -o moc_fullscreen.cpp

moc_input_widget.cpp: input_widget.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/daiyousei/sources/gizmoduck/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/daiyousei/sources/gizmoduck -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include input_widget.h -o moc_input_widget.cpp

moc_message_log.cpp: message_log.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/daiyousei/sources/gizmoduck/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/daiyousei/sources/gizmoduck -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include message_log.h -o moc_message_log.cpp

moc_tab_manager.cpp: tab_manager.h \
		webview.h \
		tab_groups.h \
		webpage.h \
		file_dialog.h \
		setting_tab.h \
		debug_tab.h \
		fullscreen.h \
		request_filter.h \
		tox_ui.h \
		input_widget.h \
		tox_client.h \
		side_tabs.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/daiyousei/sources/gizmoduck/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/daiyousei/sources/gizmoduck -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include tab_manager.h -o moc_tab_manager.cpp

moc_webview.cpp: webview.h \
		tab_groups.h \
		webpage.h \
		file_dialog.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/daiyousei/sources/gizmoduck/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/daiyousei/sources/gizmoduck -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include webview.h -o moc_webview.cpp

moc_navigation_button.cpp: navigation_button.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/daiyousei/sources/gizmoduck/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/daiyousei/sources/gizmoduck -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include navigation_button.h -o moc_navigation_button.cpp

moc_webpage.cpp: webpage.h \
		file_dialog.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/daiyousei/sources/gizmoduck/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/daiyousei/sources/gizmoduck -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include webpage.h -o moc_webpage.cpp

moc_file_dialog.cpp: file_dialog.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/daiyousei/sources/gizmoduck/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/daiyousei/sources/gizmoduck -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include file_dialog.h -o moc_file_dialog.cpp

moc_request_filter.cpp: request_filter.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/daiyousei/sources/gizmoduck/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/daiyousei/sources/gizmoduck -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include request_filter.h -o moc_request_filter.cpp

moc_side_tabs.cpp: side_tabs.h \
		webview.h \
		tab_groups.h \
		webpage.h \
		file_dialog.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/daiyousei/sources/gizmoduck/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/daiyousei/sources/gizmoduck -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include side_tabs.h -o moc_side_tabs.cpp

moc_setting_tab.cpp: setting_tab.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/daiyousei/sources/gizmoduck/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/daiyousei/sources/gizmoduck -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include setting_tab.h -o moc_setting_tab.cpp

moc_debug_tab.cpp: debug_tab.h \
		tab_groups.h \
		webpage.h \
		file_dialog.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/daiyousei/sources/gizmoduck/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/daiyousei/sources/gizmoduck -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include debug_tab.h -o moc_debug_tab.cpp

moc_tox_ui.cpp: tox_ui.h \
		input_widget.h \
		tox_client.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/daiyousei/sources/gizmoduck/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/daiyousei/sources/gizmoduck -I/usr/include/qt6 -I/usr/include/qt6/QtWebEngineWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtWebEngineCore -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtWebChannel -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtPositioning -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include tox_ui.h -o moc_tox_ui.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_qmlcache_clean compiler_qmlcache_loader_clean compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp browser_mainwindow.h \
		navigation_button.h \
		tab_manager.h \
		webview.h \
		tab_groups.h \
		webpage.h \
		file_dialog.h \
		setting_tab.h \
		debug_tab.h \
		fullscreen.h \
		request_filter.h \
		tox_ui.h \
		input_widget.h \
		tox_client.h \
		side_tabs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

browser_mainwindow.o: browser_mainwindow.cpp browser_mainwindow.h \
		navigation_button.h \
		tab_manager.h \
		webview.h \
		tab_groups.h \
		webpage.h \
		file_dialog.h \
		setting_tab.h \
		debug_tab.h \
		fullscreen.h \
		request_filter.h \
		tox_ui.h \
		input_widget.h \
		tox_client.h \
		side_tabs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o browser_mainwindow.o browser_mainwindow.cpp

fullscreen.o: fullscreen.cpp fullscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fullscreen.o fullscreen.cpp

input_widget.o: input_widget.cpp input_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o input_widget.o input_widget.cpp

message_log.o: message_log.cpp message_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o message_log.o message_log.cpp

tab_manager.o: tab_manager.cpp side_tabs.h \
		webview.h \
		tab_groups.h \
		webpage.h \
		file_dialog.h \
		tab_manager.h \
		setting_tab.h \
		debug_tab.h \
		fullscreen.h \
		request_filter.h \
		tox_ui.h \
		input_widget.h \
		tox_client.h \
		userscript.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tab_manager.o tab_manager.cpp

webview.o: webview.cpp browser_mainwindow.h \
		navigation_button.h \
		tab_manager.h \
		webview.h \
		tab_groups.h \
		webpage.h \
		file_dialog.h \
		setting_tab.h \
		debug_tab.h \
		fullscreen.h \
		request_filter.h \
		tox_ui.h \
		input_widget.h \
		tox_client.h \
		side_tabs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o webview.o webview.cpp

navigation_button.o: navigation_button.cpp navigation_button.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o navigation_button.o navigation_button.cpp

webpage.o: webpage.cpp file_dialog.h \
		webpage.h \
		webview.h \
		tab_groups.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o webpage.o webpage.cpp

file_dialog.o: file_dialog.cpp file_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o file_dialog.o file_dialog.cpp

side_tabs.o: side_tabs.cpp side_tabs.h \
		webview.h \
		tab_groups.h \
		webpage.h \
		file_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o side_tabs.o side_tabs.cpp

settings_tab.o: settings_tab.cpp file_dialog.h \
		setting_tab.h \
		tox_ui.h \
		input_widget.h \
		tox_client.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings_tab.o settings_tab.cpp

debug_tab.o: debug_tab.cpp debug_tab.h \
		tab_groups.h \
		webpage.h \
		file_dialog.h \
		message_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug_tab.o debug_tab.cpp

userscript.o: userscript.cpp userscript.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userscript.o userscript.cpp

request_filter.o: request_filter.cpp request_filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o request_filter.o request_filter.cpp

tox_client.o: tox_client.c asprintf.h \
		tox_client.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tox_client.o tox_client.c

tox_ui.o: tox_ui.cpp tox_ui.h \
		input_widget.h \
		tox_client.h \
		file_dialog.h \
		message_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tox_ui.o tox_ui.cpp

res_scripts_custom_css_js.o: res_scripts_custom_css_js.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o res_scripts_custom_css_js.o res_scripts_custom_css_js.cpp

qmlcache_loader.o: qmlcache_loader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlcache_loader.o qmlcache_loader.cpp

qrc_browser_qmlcache.o: qrc_browser_qmlcache.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_browser_qmlcache.o qrc_browser_qmlcache.cpp

moc_browser_mainwindow.o: moc_browser_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_browser_mainwindow.o moc_browser_mainwindow.cpp

moc_fullscreen.o: moc_fullscreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fullscreen.o moc_fullscreen.cpp

moc_input_widget.o: moc_input_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_input_widget.o moc_input_widget.cpp

moc_message_log.o: moc_message_log.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_message_log.o moc_message_log.cpp

moc_tab_manager.o: moc_tab_manager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tab_manager.o moc_tab_manager.cpp

moc_webview.o: moc_webview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_webview.o moc_webview.cpp

moc_navigation_button.o: moc_navigation_button.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_navigation_button.o moc_navigation_button.cpp

moc_webpage.o: moc_webpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_webpage.o moc_webpage.cpp

moc_file_dialog.o: moc_file_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_file_dialog.o moc_file_dialog.cpp

moc_request_filter.o: moc_request_filter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_request_filter.o moc_request_filter.cpp

moc_side_tabs.o: moc_side_tabs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_side_tabs.o moc_side_tabs.cpp

moc_setting_tab.o: moc_setting_tab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setting_tab.o moc_setting_tab.cpp

moc_debug_tab.o: moc_debug_tab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_debug_tab.o moc_debug_tab.cpp

moc_tox_ui.o: moc_tox_ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tox_ui.o moc_tox_ui.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

